name: Get latest release version
on:
  schedule:
    - cron:  '00 */8 * * *'
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/cruft/cruft/releases/latest | \
          jq -r ".tag_name" > current_cruft_version.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'millaguie'
          git config --global user.email 'millaguie@users.noreply.github.com'
          git commit -am "New release version"
          git push
